co/co/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
from django.contrib import admin

from main import views
from main import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]


urlpatterns += static(
    settings.STATIC_URL, 
    document_root=settings.STATIC_ROOT
)
urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

co/main/urls.py
from django.urls import path, include, reverse
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('privacy/', views.privacy, name = 'privacy'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

co/main/models.py
from django.db import models

class CallMe(models.Model):
	id = models.AutoField(primary_key=True, verbose_name='Имя')
	first_name = models.CharField(max_length=30)
	phone = models.CharField(max_length=15)
	message = models.TextField(max_length=900, null=True)
	created = models.DateTimeField(auto_now_add=True)

	class Meta:
		ordering = ['-created']
	def __str__(self):
		return self.first_name

co/main/forms.py
from django import forms
from .models import *


class CallMeForm(forms.ModelForm):
    class Meta:
        model = CallMe
        fields = ['first_name', 'phone', 'message']
        labels = {
        'first_name': 'Имя',
        'phone': 'Телефон',
        'message': 'Комментарий',
        }

co/main/views.py
import os
from django.conf import settings
from django.shortcuts import render, redirect, get_object_or_404
from .form_generator import *


def index(request):
	callme_form = handle_callme_form(request)
	context = {
		'callme_form': callme_form,
	}
	return render(request, 'main/index.html', context)


def privacy(request):
	return render(request, 'main/privacy.html')

co/main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Сайты, дизайн, иллюстрации</title>
	<link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico'%}" >

	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

	<link rel="stylesheet" href="{% static 'css/style.css' %}">

	<!-- Yandex.Metrika counter -->

	<script type="text/javascript" >
	   (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
	   m[i].l=1*new Date();
	   for (var j = 0; j < document.scripts.length; j++) {if (document.scripts[j].src === r) { return; }}
	   k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
	   (window, document, "script", "https://mc.yandex.ru/static/metrika/tag.js", "ym");
	   ym(97962435, "init", {
	        clickmap:true,
	        trackLinks:true,
	        accurateTrackBounce:true,
	        webvisor:true
	   });
	</script>
	<noscript><div><img src="https://mc.yandex.ru/static/watch/***" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
	
	<!-- /Yandex.Metrika counter -->

</head>

<body>

	<header id='header' class='py-3 brown'>
		<center>
			<a  href='{% url "main:index" %}#work'>Работы</a> | <a href='{% url "main:index" %}#who'>Обо мне</a> | <a href='{% url "main:index" %}#contact'>Контакты</a>
		</center>
	</header>

	{% block content %}
	{% endblock %}

	<footer>
		<center class='py-5'>
			<a href='https://vk.com/anna_boook'>ВКонтакте</a> | <a href='https://www.behance.net/bookannabook'>Behance</a> | <a href='https://instagram.com/anna.book.art'>Нельзяgram</a> | <a href='https://dzen.ru/v_neizvestnost'>Дзен</a>

			<p class='small pt-4 orange'>© 2024, Анна Букина</p>
		</center>
	</footer>

<script src="{% static 'js/modal_form.js' %}"></script>
</body>

</html>

co/main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}

	<section class='anima'>
		<h1>
		  <span class="hash" aria-hidden="true">#</span>
		  <span class="word">в наших жилах</span>
		  <span class="word">КОФЕ</span>
		  <span class="word">НЕ водица</span>
		</h1>
		<button>Перезапустить</button>
	</section>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.9.1/gsap.min.js"></script>
	<script src="{% static 'js/script.js' %}"></script>


	<section class='white_bg'>
		<div class='w-80'>
			
			<div id='work' class=''>
				<h2 class='brick'>Чем я могу быть полезна?</h1>

				<div class='row'>
					<div class='col-md-4'>
						<h3 id='' class="orange mx-5 pt-5">Поиграть со шрифтами</h3>
					</div>

					<div class='hero col-md-4'>
						<img class='img-fluid' src="{% static 'works/me_circle.png' %}">
					</div>
					
					<div class='col-md-4'>
						<h3 id='' class="pt-5 mx-5  brown">Внести правки в час ночи</h3>
					</div>
				</div>

			</div>
		</div>
	</section> 

	<section class='brown white_bg'>
		<div class='py-5 w-80'>

			<div class='row'>
				<div class =' col-md-6'>
					<h3 class="brick">Могу сделать сайт:</h3>
					<b><p class='pt-4'>→ Одностраничник</p></b>
					<b><p>→ Сайт-визитку</p></b>
					<b><p>→ Интернет-магазин</p></b>


					<p class='pt-5'>Разработка веб-приложений на Django.
					<p>Сборка сайтов на Wordpress и Tilda.
					<p>Интеграция самописных модулей на Jacascript.
					<p>Кастомизация дизайна веб-приложений (имела дело с Ruby on Rails, React, Elm)
					<p>Настройка e-mail рассылок.

					<p class='pt-5'>Думаю, читаю, пишу на Javascript и Python. Чуточку на PHP.

				</div>
				<div class ='col-md-6'>
					<img class='img-fluid' src="{% static 'works/site_skill.png' %}">
				</div>
			</div>

			<h3 class="brick">ТЫК:</h3>
			<center>
				<div class='row'>
					<div class ='col-md-4'>
						<p>Интернет-магазин</p>
						<a target="_blank" rel="noopener noreferrer"  href='https://new.decona.ru'><div id='decona' class='my-2  show_site'></div></a>
					</div>
					<div class ='col-md-4'>
						<p>Ещё интернет-магазин</p>
						<a target="_blank" rel="noopener noreferrer"  href='https://acoustic-panel.cosca.ru'><div id='cosca' class='my-2 show_site'></div></a>
					</div>

					<div class ='col-md-4'>
						<p>Лендинг</p>
						<a href='https://kupina-realt.ru'><div id='kupina' class='my-2  show_site'></div></a>
					</div>

				</div>
				<div class='row pt-3'>

					<div class ='col-md-4'>
						<p>Сайт стартапа</p>
						<a target="_blank" rel="noopener noreferrer"  href='https://kvant-tochka.ru'><div id='kvantto' class='my-2  show_site'></div></a>
					</div>

					<div class ='col-md-4'>
						<p>Сайт историко-патриотического проекта</p>
						<a target="_blank" rel="noopener noreferrer"  href='https://%D0%B3%D0%BE%D1%80%D0%BE%D0%B4%D0%B2%D0%BE%D0%BB%D1%88%D0%B5%D0%B1%D0%BD%D1%8B%D1%85%D0%BA%D0%BE%D1%80%D0%B0%D0%B1%D0%BB%D0%B5%D0%B9.%D1%80%D1%84'><div id='game' class='my-2  show_site'></div></a>
					</div>

					<div class ='col-md-4'>
						<p>И ещё интернет-магазин</p>
						<a href='https://spb-jara.net/'><div id='jara' class='my-2  show_site'></div></a>
					</div>

				</div>
			</center>

			<div class='row mt-5'>
				<div class ='col-md-6 pt-4'>
				
					<h3 class="mt-5 brick">А ещё:</h3>
					<p class='pt-4'>→ <b>Cделать презентацию проекта</b> с инфографикой.</p>
					<p>→ <b>Нарисовать</b> логотип, принт для футболки или толстовки, иллюстрации.</p>
					<p>Дизайн группы ВКонтакте, шапки для аккаунтов в социальных сетях.</p>
					<p>Нарисовать слои для генерации NFT-коллекции.</p>
					<p>→ <b>Сверстать</b> буклет, брошюру, флаер, афишу.</p>
					<p class='pb-2'>→ <b>Сделать для видео</b> титры, субтитры, инфографику: *.png, *.mp4.</p>


					<a target="_blank" rel="noopener noreferrer"  href='https://www.behance.net/bookannabook'><div class='my-5 white orange_bg more'>Посмотреть портфолио</div></a>

				</div>

				<div class =' col-md-6'>
					<img class='img-fluid' src="{% static 'works/cat_head.png' %}">
				</div>
			</div>


			
			
		</div>
	</section>

	<section class='white_bg'>
		<div class='py-5 w-80'>
			<div id='who' class=''>
				
				<div class='row'>
					<div class =' col-md-6'>

					  <h2 class='brick'>Кто я?</h1>
					  	<br><br>
					  	<p>Человек :)</p>
					  	<br>
					  	<p>Меня зовут Анна.</p>
						<p>Занимаюсь графическим дизайном с 2010.</p>
						<p>Свой первый сайт сделала в 2006.</p>
						<p class='pb-5'>Рисую - сколько себя помню.</p>

					</div>

					<div class ='col-md-6'>

					  <div class='scroll_it'>

					    <div class='slides'>
					    	<img src="{% static 'img/coffee.png' %}">
					    </div>
					    <div class='slides'>
					    	<img src="{% static 'img/love.png' %}">
					    </div>
					    <div class='slides'>
					    	<img src="{% static 'img/travel.png' %}">
					    </div>
					    <div class='slides'>
					    	<img src="{% static 'img/travel1.png' %}">
					    </div>
					   	<div class='slides'>
					      <img src="{% static 'img/travel2.png' %}">
					    </div>
					    <div class='slides'>
					      <img src="{% static 'img/tasks.png' %}">
					    </div>
					    <div class='slides'>
					      <img src="{% static 'img/draw.png' %}">
					    </div>
					    <div class='slides'>
					      <img src="{% static 'img/create.png' %}">
					    </div>
					    <div class='slides'>
					      <img src="{% static 'img/cats.png' %}">
					    </div>
					    <div class='slides'>
					      <img src="{% static 'img/sport.png' %}">
					    </div>
					    <div class='slides'>
					      <img src="{% static 'img/oh.png' %}">
					    </div>
					    <div class='slides'>
					      <img src="{% static 'img/diplom.png' %}">
					    </div>
					    <div class='slides'>
					      <img class='pb-2' src="{% static 'img/proj.png' %}">
					    </div>
					    <div class='slides'>
					      <img src="{% static 'img/speak.png' %}">
					    </div>
					    <div class='slides'>
					      <img src="{% static 'img/speak1.png' %}">
					    </div>
					  </div>

					</div>
				</div>

			</div>
		</div>
	</section> 

	<section class='brick_bg py-5'> 
		<div class='w-80'>
			<div id='contact' class='white'>
				<h2 class='white'>Связаться</h1>
				<p class='pt-4'>→   Пишите в телеграм <b><a class='tg_link white' href='https://t.me/anna_book'>@anna_book</a></b></p>

				<p class='pb-4'>→ Или на почту <b>ideas@coffeeinveins.ru</b></p>
				
				<section>
					{% include 'main/popup.html' %}
				</section>
			</div>
		</div>
	</section> 

{% endblock %}

co/main/templates/main/mail.html
<!doctype html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Новая заявка</title>
    <style media="all" type="text/css">
      table {
      border-collapse: separate;
      mso-table-lspace: 0pt;
      mso-table-rspace: 0pt;
      width: 100%;
      }
      body {
        color: #1b1918;
        margin: 0;
        padding: 0;
      }

      h1{
        font-size: 3.5em;
        font-weight: 550;
      }
      h5{
        font-weight: 200;
      }
      table, th, td{
        border: 2px solid #D9D9D9;
      }
      td{
        padding: 5px;
      }
      .no_border{
        border: none;
      }
    </style>
</head>

<body>
  <table class='no_border'>
    <thead></thead>
    <tbody>
      <tr>
        <td class='no_border'>
          <a href='https://coffeeinveins.ru/'><h1>Coffee</h1></a>
        </td>
        <td class='no_border'></td> <td class='no_border'></td> <td class='no_border'></td>
        <td class='no_border'>
          <p>
          <strong>Заявка № {{ callme_order.id }}</strong>
          <br>
            <span class="secondary">
              {{ callme_order.created|date:"d M, Y" }}
            </span>
          </p>
        </td>
      </tr>
    </tbody>
  </table>

  <hr>
  <br><br>

  <h3>Клиент</h3>

  <table class='no_border'>
    <thead></thead>
    <tbody>
      
      <tr>
        <td class='no_border'> <strong>Имя:</strong>
        </td>
        <td class='no_border'>{{ callme_order.first_name }}</td>
      </tr>

      <tr>
        <td class='no_border'> <strong>Телефон: </strong> 
        </td>
        <td class='no_border'>{{ callme_order.phone }}</td>
      </tr>

      <tr>
        <td class='no_border'> <strong>Комментарий: </strong> 
        </td>
        <td class='no_border'>{{ callme_order.message }}</td>
      </tr>

    </tbody>
  </table>
</body>
</html>

co/main/templates/main/popup.html
{% load static %}

<div class='modal_container' onclick='showModal(this);'>
    
  <p class='thumb white brick_bg button_form_base'>Хочу, чтобы мне перезвонили</p>

    <div class='modal_full hide'>  
      <div class=''>

        
        
        <form method="post" class="callme_container white_bg">


        	<div class='d-flex flex-row-reverse pe-3'>
	          <span class="close" onclick="closeModal(this);">&times;</span>
	        </div>

          	<center><img class='popup_big_logo' src='{% static "coffeedrink.png" %}'></center>

          	<div class='form_container brown we_300'>
            
            {% csrf_token %}


            <label for="{{ callme_form.first_name.id_for_label }}">{{ callme_form.first_name.label }}</label>
    		    {{ callme_form.first_name }}

    		    <label class='pt-2' for="{{ callme_form.phone.id_for_label }}">{{ callme_form.phone.label }}</label>
    		    {{ callme_form.phone }}

    		    <label class='pt-2' for="{{ callme_form.message.id_for_label }}">{{ callme_form.message.label }}</label>
    		    {{ callme_form.message }}

          
          <center class='py-3'><input type="submit" value="Хочу, чтобы мне перезвонили" class="button_brick"></center>

          <p class='pt-3 brick small'>* Нажимая на кнопку "Хочу, чтобы мне перезвонили", Вы соглашаетесь с <u><a class='brick' href='{% url "main:privacy" %}'>Политикой конфиденциальности</a></u>.</p>
          </div>
        </form>

      </div>
    </div>
  </div>